-- Campuses
INSERT INTO campus (id, label, name, center_lon, center_lat, zoom) VALUES
('SGW', 'SGW', 'Sir George Williams', -73.5788, 45.4972, 16.2),
('LOY', 'Loyola', 'Loyola', -73.6406, 45.4583, 16.0);

-- Buildings (SGW)
INSERT INTO building (code, campus_id, name) VALUES
('B','SGW','B Annex'),
('CI','SGW','CI Annex'),
('CL','SGW','CL Annex'),
('D','SGW','D Annex'),
('EN','SGW','EN Annex'),
('ER','SGW','ER Building'),
('EV','SGW','Engineering, Computer Science and Visual Arts Integrated Complex'),
('FA','SGW','FA Annex'),
('FB','SGW','Faubourg Building'),
('FG','SGW','Faubourg Ste-Catherine Building'),
('GA','SGW','Grey Nuns Annex'),
('GM','SGW','Guy-De Maisonneuve Building'),
('GN','SGW','Grey Nuns Building'),
('GS','SGW','GS Building'),
('H','SGW','Henry F. Hall Building'),
('K','SGW','K Annex'),
('LB','SGW','J.W. McConnell Building'),
('LD','SGW','LD Building'),
('LS','SGW','Learning Square'),
('M','SGW','M Annex'),
('MB','SGW','John Molson Building'),
('MI','SGW','MI Annex'),
('MU','SGW','MU Annex'),
('P','SGW','P Annex'),
('PR','SGW','PR Annex'),
('Q','SGW','Q Annex'),
('R','SGW','R Annex'),
('RR','SGW','RR Annex'),
('S','SGW','S Annex'),
('SB','SGW','Samuel Bronfman Building'),
('T','SGW','T Annex'),
('TD','SGW','Toronto-Dominion Building'),
('V','SGW','V Annex'),
('VA','SGW','Visual Arts Building'),
('X','SGW','X Annex'),
('Z','SGW','Z Annex');

-- Buildings (LOY)
INSERT INTO building (code, campus_id, name) VALUES
('AD','LOY','Administration Building'),
('BB','LOY','BB Annex'),
('BH','LOY','BH Annex'),
('CC','LOY','Central Building'),
('CJ','LOY','Communication Studies and Journalism Building'),
('DO','LOY','Stinger Dome'),
('FC','LOY','F.C. Smith Building'),
('GE','LOY','Centre for Structural and Functional Genomics'),
('HA','LOY','Hingston Hall, wing HA'),
('HB','LOY','Hingston Hall, wing HB'),
('HC','LOY','Hingston Hall, wing HC'),
('HU','LOY','Applied Science Hub'),
('JR','LOY','Jesuit Residence'),
('PC','LOY','PERFORM Centre'),
('PS','LOY','Physical Services Building'),
('PT','LOY','Oscar Peterson Concert Hall'),
('PY','LOY','Psychology Building'),
('QA','LOY','Quadrangle'),
('RA','LOY','Recreation and Athletics Complex'),
('RF','LOY','Loyola Jesuit Hall and Conference Centre'),
('SC','LOY','Student Centre'),
('SH','LOY','Future Buildings Laboratory'),
('SI','LOY','St. Ignatius of Loyola Church'),
('SP','LOY','Richard J. Renaud Science Complex'),
('TA','LOY','Terrebonne Building'),
('VE','LOY','Vanier Extension'),
('VL','LOY','Vanier Library Building');

-- Building addresses (SGW)
INSERT INTO building_address (building_code, address) VALUES
('B','2160 Bishop St., Montreal, QC, Canada'),
('CI','2149 Mackay St., Montreal, QC, Canada'),
('CL','1665 Ste-Catherine St. W., Montreal, QC, Canada'),
('D','2140 Bishop St., Montreal, QC, Canada'),
('EN','2070 Mackay St., Montreal, QC, Canada'),
('ER','2155 Guy St., Montreal, QC, Canada'),
('EV','1515 Ste-Catherine St. W., Montreal, QC, Canada'),
('FA','2060 Mackay St., Montreal, QC, Canada'),
('FB','1250 Guy St., Montreal, QC, Canada'),
('FB','1600 Ste-Catherine St. W., Montreal, QC, Canada'),
('FG','1610 Ste-Catherine St. W., Montreal, QC, Canada'),
('GA','1211-1215 St-Mathieu St., Montreal, QC, Canada'),
('GM','1550 De Maisonneuve Blvd. W., Montreal, QC, Canada'),
('GN','1190 Guy St., Montreal, QC, Canada'),
('GN','1175 St-Mathieu St., Montreal, QC, Canada'),
('GS','1538 Sherbrooke St. W., Montreal, QC, Canada'),
('H','1455 De Maisonneuve Blvd. W., Montreal, QC, Canada'),
('K','2150 Bishop St., Montreal, QC, Canada'),
('LB','1400 De Maisonneuve Blvd. W., Montreal, QC, Canada'),
('LD','1424 Bishop St., Montreal, QC, Canada'),
('LS','1535 De Maisonneuve Blvd. W., Montreal, QC, Canada'),
('M','2135 Mackay St., Montreal, QC, Canada'),
('MB','1450 Guy St., Montreal, QC, Canada'),
('MI','2130 Bishop St., Montreal, QC, Canada'),
('MU','2170 Bishop St., Montreal, QC, Canada'),
('P','2020 Mackay St., Montreal, QC, Canada'),
('PR','2100 Mackay St., Montreal, QC, Canada'),
('Q','2010 Mackay St., Montreal, QC, Canada'),
('R','2050 Mackay St., Montreal, QC, Canada'),
('RR','2040 Mackay St., Montreal, QC, Canada'),
('S','2145 Mackay St., Montreal, QC, Canada'),
('SB','1590 Docteur-Penfield, Montreal, QC, Canada'),
('T','2030 Mackay St., Montreal, QC, Canada'),
('TD','1410 Guy St., Montreal, QC, Canada'),
('V','2110 Mackay St., Montreal, QC, Canada'),
('VA','1395 René-Lévesque Blvd. W., Montreal, QC, Canada'),
('X','2080 Mackay St., Montreal, QC, Canada'),
('Z','2090 Mackay St., Montreal, QC, Canada');

-- Building addresses (LOY)
INSERT INTO building_address (building_code, address) VALUES
('AD','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('BB','3502 Belmore Ave., Montreal, QC, Canada'),
('BH','3500 Belmore Ave., Montreal, QC, Canada'),
('CC','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('CJ','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('DO','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('FC','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('GE','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('HA','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('HB','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('HC','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('HU','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('JR','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('PC','7200 Sherbrooke St. W., Montreal, QC, Canada'),
('PS','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('PT','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('PY','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('QA','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('RA','7200 Sherbrooke St. W., Montreal, QC, Canada'),
('RF','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('SC','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('SH','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('SI','4455 West Broadway St., Montreal, QC, Canada'),
('SP','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('TA','7079 de Terrebonne St., Montreal, QC, Canada'),
('VE','7141 Sherbrooke St. W., Montreal, QC, Canada'),
('VL','7141 Sherbrooke St. W., Montreal, QC, Canada');
