spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/hivemaps
    username: hivemaps
    password: hivemaps

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}
